apiVersion: v1
kind: Config
clusters:
- name: "teko-kubernetes"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyT1RNME1Ua3hOVEF3SGhjTk1qTXdPRE13TVRneE1qTXdXaGNOTXpNd09ESTNNVGd4TWpNdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyT1RNME1Ua3hOVEF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTdVlIZ0trdFNWZWlqKy9kQkxEQ3MzZjhVU2VOUWxqdDc2MVhMTjRYVnQKYmlKMXJwQjBKOG04ci9qeDRlSVdydlBSZE5sdGhyaTNLemEvYURrM1Nzc1JvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXBvclkvYlNRRlhIZ0VuVlAvUURXCm01b1ljMUl3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUpKMVhPYVFXbXdrUFBoUTNRdXdjNlZHdzlyN0dQV1oKRFRGazM4bGdENHp6QWlCVzZYUmlqVE0vUFk3ZDZvWWZuZkl4SnpHZDBwN01sRVFabnF2RnFReUZ4dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: "https://digital4you.internet-box.ch:6443"
contexts:
- name: "reto-pvs-teko15@teko-kubernetes"
  context:
    cluster: "teko-kubernetes"
    namespace: "pvs-teko15"
    user: "reto"
users:
- name: "reto"
  user:
    token: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImFKdXJzeXlPOEV2QkpLYVgza3IzZC04dDFfc2NxLVJMWTFBa3RXUnh5cDQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJwdnMtdGVrbzE1Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InJldG8tdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicmV0byIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQzZDBmMzQ3LWQwMjMtNGY4MC04NWQzLWMzMmZjM2FhOWUyMSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpwdnMtdGVrbzE1OnJldG8ifQ.Dqa-o6CiBEw_mKl4PcYe1_RAmWHr0SScjNBpTXi7j_FfbFv4nohfqCbznSHepgB-hF40ie9VJTEmCiyZ3y07USw7-nXxd2qXwXlxfRfbUP0Nsl8LtGaikr1qg446gEh1wpMTlXN_hj6B_LpAYJUrcPbp7cO6-YlSlQhRMKDMulTx76xn9rx55IMFUggt1p_DH_fYaGUzHPFVOnUUBMYfQ5a5Wug1AVK3MMoQ06sVDSz4x_DTMNVOAsoGB86kErpANve9WFrZyVUu4i4cspd7-3yUulT35w4hIxlbUe47rQvGnqCYqsPD-Ujg64_HnOX8KM3nUWoFCeLXwn1kiy5eYg"
current-context: "reto-pvs-teko15@teko-kubernetes"
